#!/usr/bin/env python3
"""Generate near-miss MCQ options for each concept in kb_all.json."""

import json
import random
import re
from pathlib import Path

DISTRACTOR_POOL_SIZE = 5


def topic_to_definition(topic: str) -> str:
    """Convert a topic title into a plausible short definition (~12 words)."""
    topic = topic.strip()
    if topic.startswith("What is ") or topic.startswith("What are "):
        topic = topic[8:].rstrip("?.").strip()
    parts = re.split(r"\s*(?:,|\|vs\.?|—|--|\s+and\s+)\s*", topic)
    parts = [p.strip() for p in parts if p.strip()]
    if len(parts) == 1:
        words = topic.split()
        if len(words) <= 3:
            return f"{topic} — a key concept in AI system design."
        return f"{topic} in AI systems."
    elif len(parts) == 2:
        a, b = parts
        return f"{a.strip()} and {b.strip()} as contrasting approaches in AI systems."
    elif len(parts) >= 3:
        return f"{parts[0].strip()}, {parts[1].strip()} and related aspects of AI systems."
    return topic + " in AI system design."


def score_similarity(topic_a: str, topic_b: str) -> float:
    """Score how similar two topics are (higher = better distractor)."""
    a_words = set(re.findall(r"[a-z]{3,}", topic_a.lower()))
    b_words = set(re.findall(r"[a-z]{3,}", topic_b.lower()))
    if not a_words or not b_words:
        return 0.0
    overlap = len(a_words & b_words)
    return overlap / max(len(a_words), len(b_words))


def build_distractors(topic: str, candidates: list[str]) -> list[str]:
    """Pick 3 best distractors from candidates using topic similarity."""
    if len(candidates) <= 3:
        return [topic_to_definition(c) for c in candidates]
    scored = sorted(candidates, key=lambda c: score_similarity(topic, c), reverse=True)
    pool = scored[:DISTRACTOR_POOL_SIZE]
    random.shuffle(pool)
    return [topic_to_definition(c) for c in pool[:3]]


def make_question(concept: dict) -> str:
    """Build the MCQ question text from the concept topic."""
    topic = concept["topic"].strip()
    if topic.lower().startswith("what is ") or topic.lower().startswith("what are "):
        return topic
    return f"What is {topic}?"


def generate_mcq(concept: dict, all_concepts: list[dict]) -> dict:
    """Generate MCQ for one concept."""
    topic = concept["topic"]
    module = concept["module"]
    same_module = [c for c in all_concepts if c["module"] == module and c["id"] != concept["id"]]
    cross_module = [c for c in all_concepts if c["id"] != concept["id"]]
    if len(same_module) >= 3:
        candidates = same_module
    else:
        needed = 3 - len(same_module)
        cross_sample = [c for c in cross_module if c["module"] != module][:needed]
        candidates = same_module + cross_sample
    distractor_topics = [c["topic"] for c in candidates]
    wrong_options = build_distractors(topic, distractor_topics)
    correct_answer = topic_to_definition(topic)
    options = [correct_answer] + wrong_options
    random.seed(concept["id"])
    random.shuffle(options)
    return {
        "question": make_question(concept),
        "options": options,
        "correct": options.index(correct_answer),
        "autoGenerated": True
    }


def main():
    kb_path = Path(__file__).parent / "kb_all.json"
    with open(kb_path) as f:
        kb = json.load(f)
    all_concepts = kb["concepts"]
    for concept in all_concepts:
        mcq = generate_mcq(concept, all_concepts)
        concept["mcq"] = mcq
        print(f"{concept['id']}: Q={mcq['question'][:40]}... correct_idx={mcq['correct']}")
    with open(kb_path, "w") as f:
        json.dump(kb, f, indent=2)
    print(f"\nDone — MCQ generated for {len(all_concepts)} concepts.")


if __name__ == "__main__":
    main()
